# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('team', models.CharField(choices=[('RESISTANCE', 'RESISTANCE'), ('ENLIGHTENED', 'ENLIGHTENED')], db_index=True, max_length=16)),
                ('player', models.CharField(db_index=True, max_length=32)),
                ('text', models.TextField()),
                ('action', models.CharField(blank=True, choices=[('capture', 'capture'), ('traning', 'training'), ('first_link', 'first link'), ('first_portal', 'first portal'), ('first_control_field', 'first control field'), ('link', 'link'), ('control_field', 'control field'), ('deploy', 'deploy'), ('destroy', 'destroy'), ('ada', 'ada'), ('jvs', 'jvs')], max_length=16, null=True)),
                ('action_time', models.DateTimeField()),
                ('late6', models.IntegerField(blank=True, null=True)),
                ('lnge6', models.IntegerField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommonStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=32, null=True)),
                ('staticstics_date', models.DateField()),
                ('player', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('team', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('R', 'R'), ('E', 'E')], max_length=2)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('sacsid', models.CharField(blank=True, max_length=1024, null=True)),
                ('csrf_token', models.CharField(blank=True, max_length=128, null=True)),
                ('login_latest', models.DateTimeField(blank=True, null=True)),
                ('action_latest', models.DateTimeField(auto_now=True)),
                ('need_login', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.DateTimeField(blank=True, null=True)),
                ('max_time', models.DateTimeField(blank=True, null=True)),
                ('now_time', models.DateTimeField(blank=True, null=True)),
                ('latest', models.BooleanField(default=False)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Robot')),
            ],
        ),
    ]
