# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170314_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='common',
            name='tab',
            field=models.CharField(default='all', max_length=8),
        ),
    ]
