# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_common_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonstatistics',
            name='action',
            field=models.CharField(blank=True, choices=[('capture', 'capture'), ('traning', 'training'), ('first_link', 'first link'), ('first_portal', 'first portal'), ('first_control_field', 'first control field'), ('link', 'link'), ('control_field', 'control field'), ('deploy', 'deploy'), ('destroy', 'destroy'), ('ada', 'ada'), ('jvs', 'jvs'), ('destroy_control_field', 'destroy control field'), ('destroy_link', 'destroy link')], max_length=32, null=True),
        ),
    ]
