# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_commonstatistics_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=32)),
            ],
        ),
    ]
