# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_blockad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField()),
                ('team', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('player', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='common',
            name='action',
            field=models.CharField(blank=True, choices=[('capture', 'capture'), ('traning', 'training'), ('first_link', 'first link'), ('first_portal', 'first portal'), ('first_control_field', 'first control field'), ('link', 'link'), ('control_field', 'control field'), ('deploy', 'deploy'), ('destroy', 'destroy'), ('ada', 'ada'), ('jvs', 'jvs'), ('destroy_control_field', 'destroy control field'), ('destroy_link', 'destroy link'), ('portal_fracker', 'portal fracker'), ('beacon', 'beacon')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='commonstatistics',
            name='action',
            field=models.CharField(blank=True, choices=[('capture', 'capture'), ('traning', 'training'), ('first_link', 'first link'), ('first_portal', 'first portal'), ('first_control_field', 'first control field'), ('link', 'link'), ('control_field', 'control field'), ('deploy', 'deploy'), ('destroy', 'destroy'), ('ada', 'ada'), ('jvs', 'jvs'), ('destroy_control_field', 'destroy control field'), ('destroy_link', 'destroy link'), ('portal_fracker', 'portal fracker'), ('beacon', 'beacon')], max_length=32, null=True),
        ),
    ]
